version: "3"

services:

  backend:
    image: backend
    build: .
    stop_signal: SIGINT
    environment:
      - FLASK_APP=flaskr
      - FLASK_DEBUG=True
      - MONGODB_URI=mongodb://root:example@db:27017
    ports:
      - "8090:5000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: always
